name: leon_flutter
description: "A new Flutter project."

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/images/
    - assets/logo.jpg
    - assets/images/banner.jpg