// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM55pHY6aw832rwtieGe-V8CeHFxSAdtE',
    appId: '1:202371890081:web:57d02e62683b2c3fdee9e0',
    messagingSenderId: '202371890081',
    projectId: 'topup-dm',
    authDomain: 'topup-dm.firebaseapp.com',
    storageBucket: 'topup-dm.firebasestorage.app',
    measurementId: 'G-1WKG46RLSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjiV9XDgWS25-UgUtKYcOOZ7p8H3ipfGk',
    appId: '1:202371890081:android:d882f39b1c46fdfedee9e0',
    messagingSenderId: '202371890081',
    projectId: 'topup-dm',
    storageBucket: 'topup-dm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq7OdQk9_A_un6Tn9XnQMEExO3jDZZVWY',
    appId: '1:202371890081:ios:31a17bd7621f7776dee9e0',
    messagingSenderId: '202371890081',
    projectId: 'topup-dm',
    storageBucket: 'topup-dm.firebasestorage.app',
    iosBundleId: 'com.example.leonFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq7OdQk9_A_un6Tn9XnQMEExO3jDZZVWY',
    appId: '1:202371890081:ios:31a17bd7621f7776dee9e0',
    messagingSenderId: '202371890081',
    projectId: 'topup-dm',
    storageBucket: 'topup-dm.firebasestorage.app',
    iosBundleId: 'com.example.leonFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM55pHY6aw832rwtieGe-V8CeHFxSAdtE',
    appId: '1:202371890081:web:bfbf0f6af1a7db5fdee9e0',
    messagingSenderId: '202371890081',
    projectId: 'topup-dm',
    authDomain: 'topup-dm.firebaseapp.com',
    storageBucket: 'topup-dm.firebasestorage.app',
    measurementId: 'G-NG6GZBW4C0',
  );
}
